# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'


target 'WalMart' do
    use_frameworks!
    pod 'GoogleTagManager’,’~> 3.15.0’
    pod 'AFNetworking', '~> 3.0'
    pod 'AFNetworkActivityLogger', git: 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', branch: '3_0_0'
    pod 'FBNotifications'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    pod 'TTRangeSlider'
    #Paypal payments
    pod 'PayPal-iOS-SDK', '2.16.3'
    
    #Fabric comment to commit walmart app
    pod 'Fabric'
    pod 'Crashlytics'


end
